# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "branch1" ]
  pull_request:
    branches: [ "branch1" ]

jobs:
  lint:
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v4
        - name: Super-Linter
          uses: super-linter/super-linter@v7.1.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
